// Tiny i18n layer. English strings are the keys (same as swift/Localizations); other languages
// live in i18n/<lang>.json, generated by scripts/gen-win-i18n.py from the .strings files.
let dict = {};

function t(key, ...args) {
  let s = dict[key] ?? key;
  for (const a of args) s = s.replace(/%@|%ld/, a);
  s = s.replace(/%%/g, "%");
  return s;
}

async function loadLanguage() {
  const lang = (navigator.language || "en").slice(0, 2).toLowerCase();
  document.documentElement.lang = lang;
  if (lang === "en") return;
  try {
    dict = await (await fetch(`i18n/${lang}.json`)).json();
  } catch {
    dict = {};
  }
}

// Replaces text of [data-i18n] and the title of [data-i18n-title] elements.
function applyStatic() {
  document.querySelectorAll("[data-i18n]").forEach((el) => (el.textContent = t(el.dataset.i18n)));
  document.querySelectorAll("[data-i18n-title]").forEach((el) => (el.title = t(el.dataset.i18nTitle)));
}
